### PR TITLE
testing spectral style guides

### PR DESCRIPTION
**Pull request by philsturgeon**

### CODE REVIEW

**Comment by philsturgeon** [comment]
Daft cover photo like "kicking the tyres"? https://media.gettyimages.com/photos/man-kicking-tires-at-car-lot-picture-id78024981?s=612x612

**Review by mbifulco — CHANGES_REQUESTED** [review]

**Comment by mbifulco** [comment]
Here's a nightmare cover image I made with DALLE - working on a proper one in the meantime 😂 

image

**Comment by mbifulco** [comment]
Ok just one more nightmare - 
image

**Comment by mbifulco** [comment]
Ok @philsturgeon , I'll let you pick 😂 

Option 1:

testing-style-guides-w-jest-2

Option 2:
testing-style-guides-w-jest

grab one of these, and move/rename it to `/public/images/posts/testing-spectral-style-guides-with-jest/cover.png`

**Review by mbifulco — APPROVED** [review]

**Comment by mbifulco** [comment]
@philsturgeon feel free to merge when ready - I added a cover image and updated the publish date

**Comment by philsturgeon** [comment]
Bahahaha no thank you I don’t want to reduce our readership through clown-related heart attacks!!

**Pull request merged**
