### PR TITLE
Update footer layout, and add mailing list to it

### LINKED ISSUE #519: Newsletter and Footer Improvements
Let's make our footer look more awesome, like this but use our purple for background and white text.

image

This will help us get more mailing list signups which means more books, more folks loving our articles, etc.

Let's switch to mailjet (account is in 1pass) and use their widget:

https://www.mailjet.com/feature/subscription-widget/

### PR DESCRIPTION
**Pull request by mbifulco**
Fixes #519 

This is a WIP - I need the credentials for the new newsletter form still.

@philsturgeon @matthewtrask how do you feel about the organization of the **content** here? (Will poke around with colors, etc next).  Are any links missing? Out of order? Do the various titles make sense?
image

### CODE REVIEW

**Comment by philsturgeon** [comment]
popped the mailjet creds into 1pass, sorry it was in the wrong vault. 

I think purple background with white text would be A++?

- Resources: Books, Blog, Videos, Podcast, Consulting
- Community: GitHub, Twitter, Slack, Forum, Patreon
- More Help: Consulting

The RSS links are probably not needed in the footer, we just send people to the Podcast and the RSS link should be found there instead.

I dunno if we need to keep "Built with Gatsby" and im not sure if "Made with Love" is adding much.

Could we also remove the "Not into mailing lists?" from the footer because they've most likely already seen the Slack link. It could be more like Statamic: "We send occasional newsletters..."

**Comment by mbifulco** [comment]
@philsturgeon you sure you want consulting in there twice?

**Comment by mbifulco** [comment]
This is with consulting in there once.  I also included `Code of Conduct` in Community, and bathed everything in luxurious purple:
image

**Comment by philsturgeon** [comment]
I love it! :D

**Comment by philsturgeon** [comment]
Oh hey can we fix that image spacing while we're at it? We have a lot of trouble with image positioning with resizing, i know its a pain in the butt but little bits like this make us look super pro or a bit hacky. 😆 

image

**Comment by philsturgeon** [comment]
@mbifulco is this good to go other than conflicts?

**Comment by mbifulco** [comment]
Hey Phil - I'll resolve the conflicts above.  I've got some local changes that I need to finish up and push as well.  This PR doesn't have the mailing list migrated to the new service yet

**Pull request merged**
